---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-operator
spec:
  template:
    spec:
      containers:
        - name: prometheus-operator
          resources:
            limits:
              cpu: 200m # {"$ref":"#/definitions/io.k8s.cli.setters.prometheus-operator.resources-limits-cpu"}
              memory: 200Mi # {"$ref":"#/definitions/io.k8s.cli.setters.prometheus-operator.resources-limits-memory"}
            requests:
              cpu: 100m # {"$ref":"#/definitions/io.k8s.cli.setters.prometheus-operator.resources-requests-cpu"}
              memory: 100Mi # {"$ref":"#/definitions/io.k8s.cli.setters.prometheus-operator.resources-requests-memory"}
