# https://github.com/coreos/prometheus-operator/blob/master/Documentation/user-guides/alerting.md
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: visibility
spec:
  replicas: 1 # {"$ref":"#/definitions/io.k8s.cli.setters.alertmanager.replicas"}
  externalUrl: "https://alertmanager-visibility.kube-visibility.svc:9093/" # {"$ref":"#/definitions/io.k8s.cli.setters.alertmanager.external-url"}
  retention: 120h # {"$ref":"#/definitions/io.k8s.cli.setters.alertmanager.retention"}
  logLevel: info # {"$ref":"#/definitions/io.k8s.cli.setters.alertmanager.log-level"}
  logFormat: logfmt # {"$ref":"#/definitions/io.k8s.cli.setters.alertmanager.log-format"}
  resources:
    limits:
      cpu: 100m # {"$ref":"#/definitions/io.k8s.cli.setters.alertmanager.resources-limits-cpu"}
      memory: 100Mi # {"$ref":"#/definitions/io.k8s.cli.setters.alertmanager.resources-limits-memory"}
    requests:
      cpu: 50m # {"$ref":"#/definitions/io.k8s.cli.setters.alertmanager.resources-requests-cpu"}
      memory: 50Mi # {"$ref":"#/definitions/io.k8s.cli.setters.alertmanager.resources-requests-memory"}
