apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    name: grafana
  namespace: kube-visibility # {"$ref":"#/definitions/io.k8s.cli.setters.namespace"}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: grafana
  template:
    metadata:
      labels:
        name: grafana
    spec:
      serviceAccountName: grafana
      containers:
      - name: grafana
        image: grafana/grafana:7.0.3
        ports:
        - name: http
          containerPort: 3000
        readinessProbe:
          httpGet:
            path: /api/health
            port: http
          initialDelaySeconds: 60
          periodSeconds: 30
        livenessProbe:
          httpGet:
            path: /api/health
            port: http
          initialDelaySeconds: 60
          periodSeconds: 30
        resources:
          # limits:
          #   cpu: 250m
          #   memory: 100Mi
          requests:
            cpu: 50m
            memory: 50Mi
        volumeMounts:
        - name: configuration
          mountPath: /etc/grafana/grafana.ini
          subPath: grafana.ini
          readOnly: true
        - name: dashboards-providers
          mountPath: /etc/grafana/provisioning/dashboards/providers.yaml
          subPath: providers.yaml
          readOnly: true
        - name: dashboards-datasources
          mountPath: /etc/grafana/provisioning/datasources
          readOnly: true
        - name: dashboards-prometheus-0
          mountPath: /grafana/dashboards/prometheus-0
          readOnly: true
        - name: dashboards-kubernetes-0
          mountPath: /grafana/dashboards/kubernetes-0
          readOnly: true
        - name: dashboards-kubernetes-1
          mountPath: /grafana/dashboards/kubernetes-1
          readOnly: true
        - name: dashboards-kubernetes-2
          mountPath: /grafana/dashboards/kubernetes-2
          readOnly: true
        - name: dashboards-network-0
          mountPath: /grafana/dashboards/network-0
          readOnly: true
        - name: dashboards-network-1
          mountPath: /grafana/dashboards/network-1
          readOnly: true
        - name: dashboards-infrastructure-0
          mountPath: /grafana/dashboards/infrastructure-0
          readOnly: true
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      volumes:
      - name: configuration
        configMap:
          name: configuration
      - name: dashboards-providers
        configMap:
          name: dashboards-providers
      - name: dashboards-datasources
        configMap:
          name: dashboards-datasources
      - name: dashboards-prometheus-0
        configMap:
          name: dashboards-prometheus-0
      - name: dashboards-kubernetes-0
        configMap:
          name: dashboards-kubernetes-0
      - name: dashboards-kubernetes-1
        configMap:
          name: dashboards-kubernetes-1
      - name: dashboards-kubernetes-2
        configMap:
          name: dashboards-kubernetes-2
      - name: dashboards-network-0
        configMap:
          name: dashboards-network-0
      - name: dashboards-network-1
        configMap:
          name: dashboards-network-1
      - name: dashboards-infrastructure-0
        configMap:
          name: dashboards-infrastructure-0
      nodeSelector:
        beta.kubernetes.io/os: linux
