---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    name: grafana
  namespace: kube-visibility # {"$ref":"#/definitions/io.k8s.cli.setters.namespace"}
spec:
  type: NodePort
  ports:
    - name: http
      port: 3000
      targetPort: http
  selector:
    name: grafana
