apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: visibility
  namespace: kube-visibility # {"$ref":"#/definitions/io.k8s.cli.setters.namespace"}
spec:
  replicas: 1 # {"$ref":"#/definitions/io.k8s.cli.setters.prometheus.replicas"}
  enableAdminAPI: true # {"$ref":"#/definitions/io.k8s.cli.setters.prometheus.enable-admin-api"}
  externalUrl: "https://prometheus-visibility.kube-visibility.svc:9090/" # {"$ref":"#/definitions/io.k8s.cli.setters.prometheus.external-url"}
  retention: 3w # {"$ref":"#/definitions/io.k8s.cli.setters.prometheus.retention"}
  retentionSize: 10GB # {"$ref":"#/definitions/io.k8s.cli.setters.prometheus.retention-size"}
  logLevel: debug # {"$ref":"#/definitions/io.k8s.cli.setters.prometheus.log-level"}
  logFormat: logfmt # {"$ref":"#/definitions/io.k8s.cli.setters.prometheus.log-format"}
  alerting:
    alertmanagers:
      - name: alertmanager-visibility
        namespace: kube-visibility # {"$ref":"#/definitions/io.k8s.cli.setters.namespace"}
        port: web
  resources:
    limits:
      cpu: 200m # {"$ref":"#/definitions/io.k8s.cli.setters.prometheus.resources-limits-cpu"}
      memory: 300Mi # {"$ref":"#/definitions/io.k8s.cli.setters.prometheus.resources-limits-memory"}
    requests:
      cpu: 100m # {"$ref":"#/definitions/io.k8s.cli.setters.prometheus.resources-requests-cpu"}
      memory: 200Mi # {"$ref":"#/definitions/io.k8s.cli.setters.prometheus.resources-requests-memory"}
  ruleSelector:
    matchLabels:
      role: alert-rules
      prometheus: visibility
  # affinity:
  #   podAntiAffinity:
  #     preferredDuringSchedulingIgnoredDuringExecution:
  #       - weight: 100
  #         podAffinityTerm:
  #           labelSelector:
  #             matchExpressions:
  #               - key: name
  #                 operator: In
  #                 values:
  #                   - prometheus-visibility
  #           topologyKey: "kubernetes.io/hostname"
