---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: prometheus-operator-alert-rules
  labels:
    prometheus: visibility
    role: alert-rules
spec:
  groups:
    - name: alert--prometheus-operator
      rules:
        - alert: PrometheusOperatorReconcileErrors
          annotations:
            message:
              Errors while reconciling {{ $labels.controller }} in {{ $labels.namespace
              }} Namespace.
          expr: |
            rate(prometheus_operator_reconcile_errors_total{job="prometheus-operator"}[5m]) > 0.1
          for: 10m
          labels:
            severity: warning
        - alert: PrometheusOperatorNodeLookupErrors
          annotations:
            message: Errors while reconciling Prometheus in {{ $labels.namespace }} Namespace.
          expr: |
            rate(prometheus_operator_node_address_lookup_errors_total{job="prometheus-operator"}[5m]) > 0.1
          for: 10m
          labels:
            severity: warning
