apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    name: grafana
spec:
  type: NodePort
  ports:
    - name: http
      port: 3000
      targetPort: http
  selector:
    name: grafana
