apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: kube-dns
  labels:
    k8s-app: kube-dns
    prometheus-visibility.monitoring: "enabled"
spec:
  jobLabel: kube-dns
  namespaceSelector:
    matchNames:
      - kube-system
  selector:
    matchLabels:
      k8s-app: kube-dns
  podMetricsEndpoints:
    - port: metrics
      path: "/metrics"
      scheme: http
      #bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      #bearerTokenSecret:
      interval: 15s
