apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-visibility # {"$ref":"#/definitions/io.k8s.cli.setters.namespace"}
resources:
  - service-account.yaml
  - cluster-role.yaml
  - cluster-role-binding.yaml
  - role.yaml
  - role-binding.yaml
  - service.yaml
  - deployment.yaml
  - service-monitor.yaml
