---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: aws-gp2-alertmanager-visibility
  labels:
    name: aws-gp2-alertmanager-visibility
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  fsType: ext4
reclaimPolicy: Retain
allowVolumeExpansion: true
