---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: kube-visibility
spec:
  template:
    spec:
      containers:
        - name: grafana
          resources:
            limits:
              cpu: 250m
              memory: 250Mi
            requests:
              cpu: 50m
              memory: 50Mi
          volumeMounts:
            - name: dashboards-providers-java
              mountPath: /etc/grafana/provisioning/dashboards/providers-java.yaml
              subPath: providers-java.yaml
              readOnly: true
            - name: dashboards-java
              mountPath: /grafana/dashboards/java
              readOnly: true
      volumes:
        - name: dashboards-providers-java
          configMap:
            name: dashboards-providers-java
        - name: dashboards-java
          configMap:
            name: dashboards-java
      nodeSelector: # change it, use your custom node label selectors or commet the block
        node.workload.type: management
