apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - apiserver.yaml
  - cluster-role.yaml
  - cluster-role-binding.yaml
  - cluster-role-aggregated-metrics-reader.yaml
  - cluster-role-binding-delegator.yaml
  - cluster-role-server-resources.yaml
  - hpa-resource-metrics-cluster-role-binding.yaml
  - role-binding-auth-reader.yaml
  - configmap.yaml
  - service-account.yaml
  - service.yaml
  - deployment.yaml
