apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-visibility
resources:
  - cluster-role.yaml
  - cluster-role-binding.yaml
  - cluster-role-aggregated-metrics-reader.yaml
  - cluster-role-binding-delegator.yaml
  - cluster-role-server-resources.yaml
  - role-binding-auth-reader.yaml
  - service-account.yaml
  - service.yaml
  - deployment.yaml
configMapGenerator:
  - name: prometheus-adapter-arg
    literals:
      - "prometheus-url=http://prometheus-visibility.kube-visibility.svc:9090/"
  - name: prometheus-adapter-config
    files:
      - ./configmap-content/config.yaml
