apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: resource-metrics-auth-reader
  namespace: kube-visibility # {"$ref":"#/definitions/io.k8s.cli.setters.namespace"}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
- kind: ServiceAccount
  name: prometheus-adapter
  namespace: kube-visibility # {"$ref":"#/definitions/io.k8s.cli.setters.namespace"}
