apiVersion: v1
kind: Service
metadata:
  name: prometheus-adapter
  labels:
    name: prometheus-adapter
  namespace: kube-visibility # {"$ref":"#/definitions/io.k8s.cli.setters.namespace"}
spec:
  ports:
    - name: https
      port: 443
      targetPort: 6443
  selector:
    name: prometheus-adapter
