---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-adapter
  labels:
    name: prometheus-adapter
  namespace: kube-visibility # {"$ref":"#/definitions/io.k8s.cli.setters.namespace"}
