---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-visibility # {"$ref":"#/definitions/io.k8s.cli.setters.namespace"}
bases:
  - alerting-rules/
  - recording-rules/
resources:
  - ../../../upstream/prometheus
  - service-monitor.yaml
patches:
  - prometheus-patch.yaml
