apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/version: v1.9.7
    prometheus-visibility.monitoring: "enabled" # this enable the prometheus scrapping
  name: kube-state-metrics
spec:
  jobLabel: kube-state-metrics
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-state-metrics
  namespaceSelector:
    matchNames:
      - kube-visibility # {"$ref":"#/definitions/io.k8s.cli.setters.namespace"}
  endpoints:
    - port: http-metrics
      scheme: http
      honorLabels: true
      interval: 30s
      relabelings:
        - action: labeldrop
          regex: (pod|service|endpoint|namespace)
      scrapeTimeout: 30s
    - port: telemetry
      scheme: http
      interval: 30s
