apiVersion: v1
kind: Service
metadata:
  name: alertmanager-visibility
  labels:
    alertmanager: visibility
spec:
  type: NodePort
  sessionAffinity: ClientIP
  ports:
    - name: web
      port: 9093
      targetPort: web
  selector:
    alertmanager: visibility
    app: alertmanager
