---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-visibility # {"$ref":"#/definitions/io.k8s.cli.setters.namespace"}
resources:
  - service-account.yaml
  - alertmanager.yaml
  - service.yaml
  - service-monitor.yaml

secretGenerator:
  - name: alertmanager-visibility
    files:
      - ./secrets-content/alertmanager.yaml
