apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-visibility-config
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-visibility-config
subjects:
  - kind: ServiceAccount
    name: prometheus-visibility
