---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-visibility
  labels:
    alertmanager: visibility
  namespace: kube-visibility # {"$ref":"#/definitions/io.k8s.cli.setters.namespace"}
spec:
  type: NodePort
  sessionAffinity: ClientIP
  ports:
    - name: web
      port: 9093
      targetPort: web
  selector:
    alertmanager: visibility
    app: alertmanager
