---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-visibility
  labels:
    prometheus: visibility
  namespace: kube-visibility # {"$ref":"#/definitions/io.k8s.cli.setters.namespace"}
spec:
  type: NodePort
  ports:
    - name: web
      port: 9090
      protocol: TCP
      targetPort: web
  selector:
    prometheus: visibility
    app: prometheus
