---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBindingList
items:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: prometheus
      namespace: default
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: prometheus
    subjects:
      - kind: ServiceAccount
        name: prometheus
        namespace: kube-visibility # {"$ref":"#/definitions/io.k8s.cli.setters.namespace"}
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: prometheus
      namespace: kube-system
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: prometheus
    subjects:
      - kind: ServiceAccount
        name: prometheus
        namespace: kube-visibility # {"$ref":"#/definitions/io.k8s.cli.setters.namespace"}
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: prometheus
      namespace: kube-visibility # {"$ref":"#/definitions/io.k8s.cli.setters.namespace"}
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: prometheus
    subjects:
      - kind: ServiceAccount
        name: prometheus
        namespace: kube-visibility # {"$ref":"#/definitions/io.k8s.cli.setters.namespace"}
