apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-k8s-config
  namespace: kube-visibility # {"$ref":"#/definitions/io.k8s.cli.setters.namespace"}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
