apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBindingList
items:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: prometheus
      namespace: kube-visibility
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: prometheus
    subjects:
      - kind: ServiceAccount
        name: prometheus
