apiVersion: v1
kind: Service
metadata:
  name: prometheus-adapter
  labels:
    name: prometheus-adapter
  namespace: kube-visibility
spec:
  ports:
    - name: https
      port: 443
      targetPort: 6443
  selector:
    name: prometheus-adapter
