---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: flux
  labels:
    name: flux
    kube-visibility.monitoring: "enabled" # this enable the prometheus scrapping
spec:
  jobLabel: flux
  selector:
    matchLabels:
      name: flux
      environment: production # change it if you want
  namespaceSelector:
    matchNames:
      - my-flux-namespace1 # change it
  podMetricsEndpoints:
    - targetPort: 3030
      path: /metrics
      interval: 60s
