apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-operator
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: prometheus-operator
    app.kubernetes.io/version: v0.39.0
    kube-visibility.monitoring: "enabled" # this enable the prometheus scrapping
  namespace: kube-visibility
spec:
  jobLabel: prometheus-operator
  selector:
    matchLabels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/name: prometheus-operator
      app.kubernetes.io/version: v0.39.0
  namespaceSelector:
    matchNames:
      - kube-visibility
  endpoints:
    - honorLabels: true
      port: http
