---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-scheduler
  labels:
    k8s-app: kube-scheduler
    kube-visibility.monitoring: "enabled" # this enable the prometheus scrapping
  namespace: kube-visibility # {"$ref":"#/definitions/io.k8s.cli.setters.namespace"}
spec:
  jobLabel: kube-scheduler
  namespaceSelector:
    matchNames:
      - kube-system
  selector:
    matchLabels:
      k8s-app: kube-scheduler
  endpoints:
    - port: http-metrics
      interval: 30s
