apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-visibility # {"$ref":"#/definitions/io.k8s.cli.setters.namespace"}
resources:
  - ../../../upstream/prometheus-adapter
  - apiserver.yaml
patches:
  - deployment-patch.yaml
configMapGenerator:
  - name: prometheus-adapter-arg
    behavior: merge
    literals:
      - "prometheus-url=http://prometheus-visibility.kube-visibility.svc:9090/" # {"$ref":"#/definitions/io.k8s.cli.substitutions.prometheus-adapter.prometheus-url"}
